
[functions.note-stats]
enabled = true
verify_jwt = false
import_map = "./functions/note-stats/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/note-stats/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/note-stats/*.html" ]

[functions.s3-upload-url]
enabled = true
verify_jwt = false
import_map = "./functions/s3-upload-url/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/s3-upload-url/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/s3-upload-url/*.html" ]

[functions.nombre-funcion]
enabled = true
verify_jwt = false
import_map = "./functions/nombre-funcion/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/nombre-funcion/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/nombre-funcion/*.html" ]
