name: CI/CD

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 1) traer el código
      - uses: actions/setup-node@v4 # 2) preparar Node
        with:
          node-version: 22
          cache: npm
      - run: npm ci # 3) instalar dependencias
      - run: npm run test # 4) ejecutar las pruebas
      - run: npm run build # 5) comprobar que compila
